// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.models.Customer", b =>
                {
                    b.Property<Guid>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CustomerID");

                    b.HasIndex("RoleID");

                    b.ToTable("customer");

                    b.HasData(
                        new
                        {
                            CustomerID = new Guid("b0a8a448-272a-4e92-9509-e43b963e9395"),
                            DateAdded = new DateTimeOffset(new DateTime(2022, 12, 21, 18, 49, 58, 666, DateTimeKind.Unspecified).AddTicks(3105), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2022, 12, 21, 18, 49, 58, 666, DateTimeKind.Unspecified).AddTicks(3109), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "john@mail.com",
                            Name = "John",
                            Password = "doe100",
                            Phone = "555-555-5555",
                            RoleID = 1,
                            Status = true,
                            Surname = "Doe"
                        });
                });

            modelBuilder.Entity("backend.models.models.Country", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Name = "Afghanistan",
                            Code = "AF"
                        },
                        new
                        {
                            Name = "Åland Islands",
                            Code = "AX"
                        },
                        new
                        {
                            Name = "Albania",
                            Code = "AL"
                        },
                        new
                        {
                            Name = "Algeria",
                            Code = "DZ"
                        },
                        new
                        {
                            Name = "American Samoa",
                            Code = "AS"
                        },
                        new
                        {
                            Name = "AndorrA",
                            Code = "AD"
                        },
                        new
                        {
                            Name = "Angola",
                            Code = "AO"
                        },
                        new
                        {
                            Name = "Anguilla",
                            Code = "AI"
                        },
                        new
                        {
                            Name = "Antarctica",
                            Code = "AQ"
                        },
                        new
                        {
                            Name = "Antigua and Barbuda",
                            Code = "AG"
                        },
                        new
                        {
                            Name = "Argentina",
                            Code = "AR"
                        },
                        new
                        {
                            Name = "Armenia",
                            Code = "AM"
                        },
                        new
                        {
                            Name = "Aruba",
                            Code = "AW"
                        },
                        new
                        {
                            Name = "Australia",
                            Code = "AU"
                        },
                        new
                        {
                            Name = "Austria",
                            Code = "AT"
                        },
                        new
                        {
                            Name = "Azerbaijan",
                            Code = "AZ"
                        },
                        new
                        {
                            Name = "Bahamas",
                            Code = "BS"
                        },
                        new
                        {
                            Name = "Bahrain",
                            Code = "BH"
                        },
                        new
                        {
                            Name = "Bangladesh",
                            Code = "BD"
                        },
                        new
                        {
                            Name = "Barbados",
                            Code = "BB"
                        },
                        new
                        {
                            Name = "Belarus",
                            Code = "BY"
                        },
                        new
                        {
                            Name = "Belgium",
                            Code = "BE"
                        },
                        new
                        {
                            Name = "Belize",
                            Code = "BZ"
                        },
                        new
                        {
                            Name = "Benin",
                            Code = "BJ"
                        },
                        new
                        {
                            Name = "Bermuda",
                            Code = "BM"
                        },
                        new
                        {
                            Name = "Bhutan",
                            Code = "BT"
                        },
                        new
                        {
                            Name = "Bolivia",
                            Code = "BO"
                        },
                        new
                        {
                            Name = "Bosnia and Herzegovina",
                            Code = "BA"
                        },
                        new
                        {
                            Name = "Botswana",
                            Code = "BW"
                        },
                        new
                        {
                            Name = "Bouvet Island",
                            Code = "BV"
                        },
                        new
                        {
                            Name = "Brazil",
                            Code = "BR"
                        },
                        new
                        {
                            Name = "British Indian Ocean Territory",
                            Code = "IO"
                        },
                        new
                        {
                            Name = "Brunei Darussalam",
                            Code = "BN"
                        },
                        new
                        {
                            Name = "Bulgaria",
                            Code = "BG"
                        },
                        new
                        {
                            Name = "Burkina Faso",
                            Code = "BF"
                        },
                        new
                        {
                            Name = "Burundi",
                            Code = "BI"
                        },
                        new
                        {
                            Name = "Cambodia",
                            Code = "KH"
                        },
                        new
                        {
                            Name = "Cameroon",
                            Code = "CM"
                        },
                        new
                        {
                            Name = "Canada",
                            Code = "CA"
                        },
                        new
                        {
                            Name = "Cape Verde",
                            Code = "CV"
                        },
                        new
                        {
                            Name = "Cayman Islands",
                            Code = "KY"
                        },
                        new
                        {
                            Name = "Central African Republic",
                            Code = "CF"
                        },
                        new
                        {
                            Name = "Chad",
                            Code = "TD"
                        },
                        new
                        {
                            Name = "Chile",
                            Code = "CL"
                        },
                        new
                        {
                            Name = "China",
                            Code = "CN"
                        },
                        new
                        {
                            Name = "Christmas Island",
                            Code = "CX"
                        },
                        new
                        {
                            Name = "Cocos (Keeling) Islands",
                            Code = "CC"
                        },
                        new
                        {
                            Name = "Colombia",
                            Code = "CO"
                        },
                        new
                        {
                            Name = "Comoros",
                            Code = "KM"
                        },
                        new
                        {
                            Name = "Congo",
                            Code = "CG"
                        },
                        new
                        {
                            Name = "Congo, The Democratic Republic of the",
                            Code = "CD"
                        },
                        new
                        {
                            Name = "Cook Islands",
                            Code = "CK"
                        },
                        new
                        {
                            Name = "Costa Rica",
                            Code = "CR"
                        },
                        new
                        {
                            Name = "Cote D'Ivoire",
                            Code = "CI"
                        },
                        new
                        {
                            Name = "Croatia",
                            Code = "HR"
                        },
                        new
                        {
                            Name = "Cuba",
                            Code = "CU"
                        },
                        new
                        {
                            Name = "Cyprus",
                            Code = "CY"
                        },
                        new
                        {
                            Name = "Czech Republic",
                            Code = "CZ"
                        },
                        new
                        {
                            Name = "Denmark",
                            Code = "DK"
                        },
                        new
                        {
                            Name = "Djibouti",
                            Code = "DJ"
                        },
                        new
                        {
                            Name = "Dominica",
                            Code = "DM"
                        },
                        new
                        {
                            Name = "Dominican Republic",
                            Code = "DO"
                        },
                        new
                        {
                            Name = "Ecuador",
                            Code = "EC"
                        },
                        new
                        {
                            Name = "Egypt",
                            Code = "EG"
                        },
                        new
                        {
                            Name = "El Salvador",
                            Code = "SV"
                        },
                        new
                        {
                            Name = "Equatorial Guinea",
                            Code = "GQ"
                        },
                        new
                        {
                            Name = "Eritrea",
                            Code = "ER"
                        },
                        new
                        {
                            Name = "Estonia",
                            Code = "EE"
                        },
                        new
                        {
                            Name = "Ethiopia",
                            Code = "ET"
                        },
                        new
                        {
                            Name = "Falkland Islands (Malvinas)",
                            Code = "FK"
                        },
                        new
                        {
                            Name = "Faroe Islands",
                            Code = "FO"
                        },
                        new
                        {
                            Name = "Fiji",
                            Code = "FJ"
                        },
                        new
                        {
                            Name = "Finland",
                            Code = "FI"
                        },
                        new
                        {
                            Name = "France",
                            Code = "FR"
                        },
                        new
                        {
                            Name = "French Guiana",
                            Code = "GF"
                        },
                        new
                        {
                            Name = "French Polynesia",
                            Code = "PF"
                        },
                        new
                        {
                            Name = "French Southern Territories",
                            Code = "TF"
                        },
                        new
                        {
                            Name = "Gabon",
                            Code = "GA"
                        },
                        new
                        {
                            Name = "Gambia",
                            Code = "GM"
                        },
                        new
                        {
                            Name = "Georgia",
                            Code = "GE"
                        },
                        new
                        {
                            Name = "Germany",
                            Code = "DE"
                        },
                        new
                        {
                            Name = "Ghana",
                            Code = "GH"
                        },
                        new
                        {
                            Name = "Gibraltar",
                            Code = "GI"
                        },
                        new
                        {
                            Name = "Greece",
                            Code = "GR"
                        },
                        new
                        {
                            Name = "Greenland",
                            Code = "GL"
                        },
                        new
                        {
                            Name = "Grenada",
                            Code = "GD"
                        },
                        new
                        {
                            Name = "Guadeloupe",
                            Code = "GP"
                        },
                        new
                        {
                            Name = "Guam",
                            Code = "GU"
                        },
                        new
                        {
                            Name = "Guatemala",
                            Code = "GT"
                        },
                        new
                        {
                            Name = "Guernsey",
                            Code = "GG"
                        },
                        new
                        {
                            Name = "Guinea",
                            Code = "GN"
                        },
                        new
                        {
                            Name = "Guinea-Bissau",
                            Code = "GW"
                        },
                        new
                        {
                            Name = "Guyana",
                            Code = "GY"
                        },
                        new
                        {
                            Name = "Haiti",
                            Code = "HT"
                        },
                        new
                        {
                            Name = "Heard Island and Mcdonald Islands",
                            Code = "HM"
                        },
                        new
                        {
                            Name = "Holy See (Vatican City State)",
                            Code = "VA"
                        },
                        new
                        {
                            Name = "Honduras",
                            Code = "HN"
                        },
                        new
                        {
                            Name = "Hong Kong",
                            Code = "HK"
                        },
                        new
                        {
                            Name = "Hungary",
                            Code = "HU"
                        },
                        new
                        {
                            Name = "Iceland",
                            Code = "IS"
                        },
                        new
                        {
                            Name = "India",
                            Code = "IN"
                        },
                        new
                        {
                            Name = "Indonesia",
                            Code = "ID"
                        },
                        new
                        {
                            Name = "Iran, Islamic Republic Of",
                            Code = "IR"
                        },
                        new
                        {
                            Name = "Iraq",
                            Code = "IQ"
                        },
                        new
                        {
                            Name = "Ireland",
                            Code = "IE"
                        },
                        new
                        {
                            Name = "Isle of Man",
                            Code = "IM"
                        },
                        new
                        {
                            Name = "Israel",
                            Code = "IL"
                        },
                        new
                        {
                            Name = "Italy",
                            Code = "IT"
                        },
                        new
                        {
                            Name = "Jamaica",
                            Code = "JM"
                        },
                        new
                        {
                            Name = "Japan",
                            Code = "JP"
                        },
                        new
                        {
                            Name = "Jersey",
                            Code = "JE"
                        },
                        new
                        {
                            Name = "Jordan",
                            Code = "JO"
                        },
                        new
                        {
                            Name = "Kazakhstan",
                            Code = "KZ"
                        },
                        new
                        {
                            Name = "Kenya",
                            Code = "KE"
                        },
                        new
                        {
                            Name = "Kiribati",
                            Code = "KI"
                        },
                        new
                        {
                            Name = "Korea, Democratic People'S Republic of",
                            Code = "KP"
                        },
                        new
                        {
                            Name = "Korea, Republic of",
                            Code = "KR"
                        },
                        new
                        {
                            Name = "Kuwait",
                            Code = "KW"
                        },
                        new
                        {
                            Name = "Kyrgyzstan",
                            Code = "KG"
                        },
                        new
                        {
                            Name = "Lao People'S Democratic Republic",
                            Code = "LA"
                        },
                        new
                        {
                            Name = "Latvia",
                            Code = "LV"
                        },
                        new
                        {
                            Name = "Lebanon",
                            Code = "LB"
                        },
                        new
                        {
                            Name = "Lesotho",
                            Code = "LS"
                        },
                        new
                        {
                            Name = "Liberia",
                            Code = "LR"
                        },
                        new
                        {
                            Name = "Libyan Arab Jamahiriya",
                            Code = "LY"
                        },
                        new
                        {
                            Name = "Liechtenstein",
                            Code = "LI"
                        },
                        new
                        {
                            Name = "Lithuania",
                            Code = "LT"
                        },
                        new
                        {
                            Name = "Luxembourg",
                            Code = "LU"
                        },
                        new
                        {
                            Name = "Macao",
                            Code = "MO"
                        },
                        new
                        {
                            Name = "Macedonia, The Former Yugoslav Republic of",
                            Code = "MK"
                        },
                        new
                        {
                            Name = "Madagascar",
                            Code = "MG"
                        },
                        new
                        {
                            Name = "Malawi",
                            Code = "MW"
                        },
                        new
                        {
                            Name = "Malaysia",
                            Code = "MY"
                        },
                        new
                        {
                            Name = "Maldives",
                            Code = "MV"
                        },
                        new
                        {
                            Name = "Mali",
                            Code = "ML"
                        },
                        new
                        {
                            Name = "Malta",
                            Code = "MT"
                        },
                        new
                        {
                            Name = "Marshall Islands",
                            Code = "MH"
                        },
                        new
                        {
                            Name = "Martinique",
                            Code = "MQ"
                        },
                        new
                        {
                            Name = "Mauritania",
                            Code = "MR"
                        },
                        new
                        {
                            Name = "Mauritius",
                            Code = "MU"
                        },
                        new
                        {
                            Name = "Mayotte",
                            Code = "YT"
                        },
                        new
                        {
                            Name = "Mexico",
                            Code = "MX"
                        },
                        new
                        {
                            Name = "Micronesia, Federated States of",
                            Code = "FM"
                        },
                        new
                        {
                            Name = "Moldova, Republic of",
                            Code = "MD"
                        },
                        new
                        {
                            Name = "Monaco",
                            Code = "MC"
                        },
                        new
                        {
                            Name = "Mongolia",
                            Code = "MN"
                        },
                        new
                        {
                            Name = "Montserrat",
                            Code = "MS"
                        },
                        new
                        {
                            Name = "Morocco",
                            Code = "MA"
                        },
                        new
                        {
                            Name = "Mozambique",
                            Code = "MZ"
                        },
                        new
                        {
                            Name = "Myanmar",
                            Code = "MM"
                        },
                        new
                        {
                            Name = "Namibia",
                            Code = "NA"
                        },
                        new
                        {
                            Name = "Nauru",
                            Code = "NR"
                        },
                        new
                        {
                            Name = "Nepal",
                            Code = "NP"
                        },
                        new
                        {
                            Name = "Netherlands",
                            Code = "NL"
                        },
                        new
                        {
                            Name = "Netherlands Antilles",
                            Code = "AN"
                        },
                        new
                        {
                            Name = "New Caledonia",
                            Code = "NC"
                        },
                        new
                        {
                            Name = "New Zealand",
                            Code = "NZ"
                        },
                        new
                        {
                            Name = "Nicaragua",
                            Code = "NI"
                        },
                        new
                        {
                            Name = "Niger",
                            Code = "NE"
                        },
                        new
                        {
                            Name = "Nigeria",
                            Code = "NG"
                        },
                        new
                        {
                            Name = "Niue",
                            Code = "NU"
                        },
                        new
                        {
                            Name = "Norfolk Island",
                            Code = "NF"
                        },
                        new
                        {
                            Name = "Northern Mariana Islands",
                            Code = "MP"
                        },
                        new
                        {
                            Name = "Norway",
                            Code = "NO"
                        },
                        new
                        {
                            Name = "Oman",
                            Code = "OM"
                        },
                        new
                        {
                            Name = "Pakistan",
                            Code = "PK"
                        },
                        new
                        {
                            Name = "Palau",
                            Code = "PW"
                        },
                        new
                        {
                            Name = "Palestinian Territory, Occupied",
                            Code = "PS"
                        },
                        new
                        {
                            Name = "Panama",
                            Code = "PA"
                        },
                        new
                        {
                            Name = "Papua New Guinea",
                            Code = "PG"
                        },
                        new
                        {
                            Name = "Paraguay",
                            Code = "PY"
                        },
                        new
                        {
                            Name = "Peru",
                            Code = "PE"
                        },
                        new
                        {
                            Name = "Philippines",
                            Code = "PH"
                        },
                        new
                        {
                            Name = "Pitcairn",
                            Code = "PN"
                        },
                        new
                        {
                            Name = "Poland",
                            Code = "PL"
                        },
                        new
                        {
                            Name = "Portugal",
                            Code = "PT"
                        },
                        new
                        {
                            Name = "Puerto Rico",
                            Code = "PR"
                        },
                        new
                        {
                            Name = "Qatar",
                            Code = "QA"
                        },
                        new
                        {
                            Name = "Reunion",
                            Code = "RE"
                        },
                        new
                        {
                            Name = "Romania",
                            Code = "RO"
                        },
                        new
                        {
                            Name = "Russian Federation",
                            Code = "RU"
                        },
                        new
                        {
                            Name = "RWANDA",
                            Code = "RW"
                        },
                        new
                        {
                            Name = "Saint Helena",
                            Code = "SH"
                        },
                        new
                        {
                            Name = "Saint Kitts and Nevis",
                            Code = "KN"
                        },
                        new
                        {
                            Name = "Saint Lucia",
                            Code = "LC"
                        },
                        new
                        {
                            Name = "Saint Pierre and Miquelon",
                            Code = "PM"
                        },
                        new
                        {
                            Name = "Saint Vincent and the Grenadines",
                            Code = "VC"
                        },
                        new
                        {
                            Name = "Samoa",
                            Code = "WS"
                        },
                        new
                        {
                            Name = "San Marino",
                            Code = "SM"
                        },
                        new
                        {
                            Name = "Sao Tome and Principe",
                            Code = "ST"
                        },
                        new
                        {
                            Name = "Saudi Arabia",
                            Code = "SA"
                        },
                        new
                        {
                            Name = "Senegal",
                            Code = "SN"
                        },
                        new
                        {
                            Name = "Serbia and Montenegro",
                            Code = "CS"
                        },
                        new
                        {
                            Name = "Seychelles",
                            Code = "SC"
                        },
                        new
                        {
                            Name = "Sierra Leone",
                            Code = "SL"
                        },
                        new
                        {
                            Name = "Singapore",
                            Code = "SG"
                        },
                        new
                        {
                            Name = "Slovakia",
                            Code = "SK"
                        },
                        new
                        {
                            Name = "Slovenia",
                            Code = "SI"
                        },
                        new
                        {
                            Name = "Solomon Islands",
                            Code = "SB"
                        },
                        new
                        {
                            Name = "Somalia",
                            Code = "SO"
                        },
                        new
                        {
                            Name = "South Africa",
                            Code = "ZA"
                        },
                        new
                        {
                            Name = "South Georgia and the South Sandwich Islands",
                            Code = "GS"
                        },
                        new
                        {
                            Name = "Spain",
                            Code = "ES"
                        },
                        new
                        {
                            Name = "Sri Lanka",
                            Code = "LK"
                        },
                        new
                        {
                            Name = "Sudan",
                            Code = "SD"
                        },
                        new
                        {
                            Name = "Suriname",
                            Code = "SR"
                        },
                        new
                        {
                            Name = "Svalbard and Jan Mayen",
                            Code = "SJ"
                        },
                        new
                        {
                            Name = "Swaziland",
                            Code = "SZ"
                        },
                        new
                        {
                            Name = "Sweden",
                            Code = "SE"
                        },
                        new
                        {
                            Name = "Switzerland",
                            Code = "CH"
                        },
                        new
                        {
                            Name = "Syrian Arab Republic",
                            Code = "SY"
                        },
                        new
                        {
                            Name = "Taiwan, Province of China",
                            Code = "TW"
                        },
                        new
                        {
                            Name = "Tajikistan",
                            Code = "TJ"
                        },
                        new
                        {
                            Name = "Tanzania, United Republic of",
                            Code = "TZ"
                        },
                        new
                        {
                            Name = "Thailand",
                            Code = "TH"
                        },
                        new
                        {
                            Name = "Timor-Leste",
                            Code = "TL"
                        },
                        new
                        {
                            Name = "Togo",
                            Code = "TG"
                        },
                        new
                        {
                            Name = "Tokelau",
                            Code = "TK"
                        },
                        new
                        {
                            Name = "Tonga",
                            Code = "TO"
                        },
                        new
                        {
                            Name = "Trinidad and Tobago",
                            Code = "TT"
                        },
                        new
                        {
                            Name = "Tunisia",
                            Code = "TN"
                        },
                        new
                        {
                            Name = "Turkey",
                            Code = "TR"
                        },
                        new
                        {
                            Name = "Turkmenistan",
                            Code = "TM"
                        },
                        new
                        {
                            Name = "Turks and Caicos Islands",
                            Code = "TC"
                        },
                        new
                        {
                            Name = "Tuvalu",
                            Code = "TV"
                        },
                        new
                        {
                            Name = "Uganda",
                            Code = "UG"
                        },
                        new
                        {
                            Name = "Ukraine",
                            Code = "UA"
                        },
                        new
                        {
                            Name = "United Arab Emirates",
                            Code = "AE"
                        },
                        new
                        {
                            Name = "United Kingdom",
                            Code = "GB"
                        },
                        new
                        {
                            Name = "United States",
                            Code = "US"
                        },
                        new
                        {
                            Name = "United States Minor Outlying Islands",
                            Code = "UM"
                        },
                        new
                        {
                            Name = "Uruguay",
                            Code = "UY"
                        },
                        new
                        {
                            Name = "Uzbekistan",
                            Code = "UZ"
                        },
                        new
                        {
                            Name = "Vanuatu",
                            Code = "VU"
                        },
                        new
                        {
                            Name = "Venezuela",
                            Code = "VE"
                        },
                        new
                        {
                            Name = "Viet Nam",
                            Code = "VN"
                        },
                        new
                        {
                            Name = "Virgin Islands, British",
                            Code = "VG"
                        },
                        new
                        {
                            Name = "Virgin Islands, U.S.",
                            Code = "VI"
                        },
                        new
                        {
                            Name = "Wallis and Futuna",
                            Code = "WF"
                        },
                        new
                        {
                            Name = "Western Sahara",
                            Code = "EH"
                        },
                        new
                        {
                            Name = "Yemen",
                            Code = "YE"
                        },
                        new
                        {
                            Name = "Zambia",
                            Code = "ZM"
                        },
                        new
                        {
                            Name = "Zimbabwe",
                            Code = "ZW"
                        });
                });

            modelBuilder.Entity("backend.models.models.CustomerCollection", b =>
                {
                    b.Property<Guid>("CCID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CPID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CCID");

                    b.HasIndex("CPID");

                    b.HasIndex("CustomerID");

                    b.ToTable("customer_collection");
                });

            modelBuilder.Entity("backend.models.models.CustomerProduct", b =>
                {
                    b.Property<Guid>("CPID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Products")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Subtotal")
                        .HasColumnType("double precision");

                    b.HasKey("CPID");

                    b.HasIndex("CustomerID");

                    b.ToTable("customer_product");
                });

            modelBuilder.Entity("backend.models.models.Delivery", b =>
                {
                    b.Property<Guid>("OrderID")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("boolean");

                    b.HasKey("OrderID");

                    b.ToTable("delivery");
                });

            modelBuilder.Entity("backend.models.models.Order", b =>
                {
                    b.Property<Guid>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CCID")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("OrderTotal")
                        .HasColumnType("double precision");

                    b.HasKey("OrderID");

                    b.HasIndex("CCID");

                    b.ToTable("order");
                });

            modelBuilder.Entity("backend.models.models.Product", b =>
                {
                    b.Property<Guid>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Desc")
                        .HasColumnType("text");

                    b.Property<string>("ImageName")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("InStock")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PDTypeID")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("ProductID");

                    b.HasIndex("PDTypeID");

                    b.ToTable("product");
                });

            modelBuilder.Entity("backend.models.models.ProductType", b =>
                {
                    b.Property<int>("PDTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PDTypeID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PDTypeID");

                    b.ToTable("product_type");

                    b.HasData(
                        new
                        {
                            PDTypeID = 1,
                            Category = "Beverages"
                        },
                        new
                        {
                            PDTypeID = 2,
                            Category = "Grains"
                        });
                });

            modelBuilder.Entity("backend.models.models.Roles", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleID");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleID = 2,
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("backend.models.models.Shipping", b =>
                {
                    b.Property<int>("ShippingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShippingID"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PostalCode")
                        .HasColumnType("integer");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ShippingID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("Name");

                    b.ToTable("shipping");
                });

            modelBuilder.Entity("backend.models.Customer", b =>
                {
                    b.HasOne("backend.models.models.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("backend.models.models.CustomerCollection", b =>
                {
                    b.HasOne("backend.models.models.CustomerProduct", "CustomerProduct")
                        .WithMany()
                        .HasForeignKey("CPID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("CustomerProduct");
                });

            modelBuilder.Entity("backend.models.models.CustomerProduct", b =>
                {
                    b.HasOne("backend.models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("backend.models.models.Delivery", b =>
                {
                    b.HasOne("backend.models.models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("backend.models.models.Order", b =>
                {
                    b.HasOne("backend.models.models.CustomerCollection", "CustomerCollection")
                        .WithMany()
                        .HasForeignKey("CCID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerCollection");
                });

            modelBuilder.Entity("backend.models.models.Product", b =>
                {
                    b.HasOne("backend.models.models.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("PDTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("backend.models.models.Shipping", b =>
                {
                    b.HasOne("backend.models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.models.models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("Name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
